# Tell Java exactly where your local Docker PostgreSQL database container is listening
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Prevent Java from trying to overwrite the table migrations you already ran manually
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true